### ISSUE TITLE
和mdict-query里的readmdict.py不一样

### ISSUE THREAD

**Issue by redstoneleo** [liuyug/mdict-utils#1]
阁下的
https://github.com/liuyug/mdict-utils/blob/master/mdict_utils/base/readmdict.py
和
https://github.com/mmjang/mdict-query
里的readmdict.py不一样，请问这种改动是不是做了些优化呢还是……？希望给点介绍，正在纠结要用那个项目

**Comment by redstoneleo** [comment]
另外，我发现查单词的算法还没有优化是不是？所以速度有点慢？
https://github.com/liuyug/mdict-utils/blob/master/mdict_utils/reader.py#L138

**Comment by liuyug** [comment]
1. 我的是原版搬过来的，他的经过改变
2. 这个工具不是为了查询，提供查询只是为了验证数据是否正确。

**Comment by redstoneleo** [comment]
我觉得有必要在项目描述里说明本项目的目的（不是为了查询），以免引起不必要的纠结~

**Comment by liuyug** [comment]
有道理
