### ISSUE TITLE
all same entry, with different meanings won't be returned

### ISSUE THREAD

**Issue by 0xdolan** [liuyug/mdict-utils#11]
When there is an entry with more than one meaning BUT **same spelling**, what is the easiest way to return all of them. As I couldn't find any.
query('test.mdx', entry,) --> it will return only one of them.

**Comment by liuyug** [comment]
It is a packing and unpacking tool, not for query word that is simple test to validate your just packed MDX file.

**Comment by dolanskurd** [comment]
That's fine. I will find another way for now, but it would be better to be taken into account for your future updates. It can be used also for searching. It would be a nice feature. 
Thanks, by the way, for your great repo.
