### ISSUE TITLE
query a key that starts with dash

### ISSUE THREAD

**Issue by faridcher** [liuyug/mdict-utils#12]
I have tried the followings:

```bash
mdict -q '-ment' oald9.mdx
usage: mdict [-h] [--version] [-k] [-m] [-q <key>] [--txt-db] [--db-txt] [-x] [-d <exdir>] [--exdb] [--exdb-zip] [--split-n <number>]
             [--split-az] [-a <resource>] [--title <title>] [--description <description>] [--encoding <encoding>] [--key-size <size>]
             [--record-size <size>] [--key-file <key file>] [--convert-chtml]
             <mdx/mdd>
mdict: error: argument -q: expected one argument
```

I get the same error when using double dashes to declare the end of options:
```bash
mdict -q -- '-ment' ${f}oald9.mdx
```

**Comment by liuyug** [comment]
It's linux shell and "mdict“ issue

1. linux shell
double dash(--) is for position arguments not for option arguments. So command should be ```mdict -q  "\-ment"  oald9.mdx```

2. mdict
python do not filter prefix backslash("\"), so fix it.

have updated code, please try again.

**Comment by faridcher** [comment]
In Linux Shell double dashes specifies the end of a command options not positional arguments. see [here](https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean). By the way your update fixed it. thank you.
