### ISSUE TITLE
好像不支持带空格的文件名？

### ISSUE THREAD

**Issue by VimWei** [liuyug/mdict-utils#13]
当输入输出的文件名带有空格时，不能运行。

请求使用方法，或升级支援。

**Comment by liuyug** [comment]
![image](https://user-images.githubusercontent.com/612758/141390826-8fe7ae92-684f-42fb-8654-ba3726f0d18c.png)

文件名可以有空格！

**Comment by VimWei** [comment]
明白了，空格需要使用\转义处理。

**Comment by VimWei** [comment]
> ![image](https://user-images.githubusercontent.com/612758/141390826-8fe7ae92-684f-42fb-8654-ba3726f0d18c.png)
> 
> 文件名可以有空格！

您这是在Linux下运行的吗？我使用Windows，经测试好像只能使用“a b c.txt” , 而不能使用 a\ b\ c.txt

有办法能够兼容不同平台的处理方法吗?

**Comment by VimWei** [comment]
这是运行截图：

![2021-11-12_110008](https://user-images.githubusercontent.com/25874852/141401732-74731066-1f06-48f4-a997-77289e0ae6b5.png)

**Comment by VimWei** [comment]
Windows下 单引号也不行，还必须是双引号。

![image](https://user-images.githubusercontent.com/25874852/141402853-913df299-e39b-4ed2-8dd0-c0477592e958.png)

**Comment by VimWei** [comment]
请问有办法能够兼容不同平台的处理方法吗? （我不熟悉Linux 或 mac）

**Comment by liuyug** [comment]
“ ” 也适用于 Linux 和 Mac 系统。

文件名这类的问题属于操作平台，与应用无关。

**Comment by liuyug** [comment]
![image](https://user-images.githubusercontent.com/612758/142158804-b8026931-bcf7-4276-9442-ba8e105889fc.png)
