### ISSUE TITLE
Adding single file to MDD file removes all existing keys

### ISSUE THREAD

**Issue by glowinthedark** [liuyug/mdict-utils#19]
Assuming the file `ldoce6.mdd` **already exists** and has data in it, running the command below removes _all the data_, and replaces with the given file:

```bash
mdict -a style.css ldoce6.mdd
```

### Expected result:
- existing data in `ldoce6.mdd` is preserved and `style.css` is added to existing keys.

### Actual result:
- all existing keys are removed and the file only contains the key `style.css`.

#### Notes

It must be possible to add new keys to an existing mdx/mdd file without having to unpack and repack _everything_.

**Comment by liuyug** [comment]
It do not support to modify file because the file format MDX is only for reading but not writing.

**Comment by glowinthedark** [comment]
does the above also apply to MDD? I would assume yes..

anyway, the cheap workaround I found is to simply use _another_ mdd file, given that a file such as `ldoce6.mdx` might have multiple MDD files, e.g. `ldoce6.mdd`,  `ldoce6.1.mdd`, `ldoce6.2.mdd`, etc and this is supported by the MDict apps and pyglossary, so the issue can be considered closed.

**Comment by liuyug** [comment]
MDX and MDD are the same file struct that are for reading.
Adding many MDD files is best solution.
