### ISSUE TITLE
errror happens when save the output to clipboard or text file

### ISSUE THREAD

**Issue by valuex** [liuyug/mdict-utils#2]
in the file `__main__.py`,  line 82: `print(record)` is used to print results to stdout.  
But when there are some Chinese characters in the returned results,  to use `print `  directly will return error message as:  
`UnicodeEncodeError: 'gbk' codec can't encode character '\u2027' in position 208: illegal multibyte sequence`

After searching, I added three lines in the `__main__.py`, then no more error message.  
```
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf8')
```
Hope this is helpful to anyone has the same error.

if in CMD window, the Chinese characters are still messed up codes. Try to run 
`chcp 65001`, that is to change CodePage
and then the Chinese characters  can be well presented.

**Comment by liuyug** [comment]
Yes, it is encoding error in difference console.The default encoding is utf-8. 
In windows, use "chcp 65001 to change to utf-8 encoding or run it in "powershell".

**Comment by kysterics** [comment]
> Yes, it is encoding error in difference console.The default encoding is utf-8.
> In windows, use "chcp 65001 to change to utf-8 encoding or run it in "powershell".

I'm using mdict.exe on windows. I tried both of the solutions but it still returned `Traceback (most recent call last):
  File "C:\home\Projects\dev\mdict\build\mdict_utils\mdict-script.py", line 2, in <module>
  File "mdict_utils\__main__.py", line 123, in run
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 874: illegal multibyte sequence
[41700] Failed to execute script mdict-script`. Any idea why?

**Comment by liuyug** [comment]
Your issue is file encoding.

1.  Update latest version firstly.  ```pip install -U mdict_utils```

2. Check your description.html file.  All files must be UTF-8 encoding
