### ISSUE TITLE
convert-chtml converts "@@@LINK=" to empty line

### ISSUE THREAD

**Issue by epistularum** [liuyug/mdict-utils#20]
For instance:
```
a
@@@LINK=b
</>
```
Becomes:
```
a

</>
```

**Comment by epistularum** [comment]
Yes that is the issue. Currently using convert-chtml is bugged because it removes those lines.

**Comment by liuyug** [comment]
have fix the bug but I do not test for no test mdx file.
May you help pull and test it?
