### ISSUE TITLE
打包的词典在欧陆词典 iOS 版上查询加载缓慢的问题

### ISSUE THREAD

**Issue by zhongao** [liuyug/mdict-utils#4]
你的工具还蛮好用，感谢一下。

我碰到的问题，用 writemdict 和 mdict_utils 生成的 mdx 在 iOS 欧陆下面，能用，但查词非常缓慢。

**Comment by liuyug** [comment]
是不是词典太大了或者词条索引太多了
可以先打包部分词条试试，如只打包 a-h 开头的词
还可以换其他的词典软件试试，如goldendict
