### ISSUE TITLE
建议：增加在Python交互模式下以函数方法调用的API

### ISSUE THREAD

**Issue by matrixChimera** [liuyug/mdict-utils#5]
### 问题现状：
当前该项目仅有命令行模式的调用方法，**无法以函数方式调用**。

### 改进建议：
增加Python交互模式下（.py文件中、模块间）以函数API调用的方法，以便他人在导入此项目的模块时使用更方便的函数API调用该项目。

### 需求实例：
在本人使用py2app.py开发的ZipMdict.app（[适用于Mac平台的mdict打包&解压工具](https://github.com/matrixChimera/ZipMdict)）中，非常希望以调用函数的方式调用您的此项目中的.mdd打包功能：

<img width="941" alt="在py中调用" src="https://user-images.githubusercontent.com/51223743/82650388-38f1b180-9c4d-11ea-86e6-1f177e31587d.png">

但将上述代码所在的ZipMdict.py文件使用py2app.py打包为ZipMdict.app后，尽管已在setup.py中添加了您的此项目，但仍无法成功调用您此项目中的.mdd打包功能：

```python
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ZipMdict.py']
DATA_FILES = ['logo_128.png']
OPTIONS = {
    'iconfile':'icon.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    py_modules=['readmdict', 'ripemd128', 'pureSalsa20', 'writemdict', 'mdict_utils']
)
```

敬请指导 🙏

**Comment by liuyug** [comment]
py_modules=['mdict_utils'] 和 os.system('mdict') ... 这个两个怎么能匹配。

无法回答你的问题
