### ISSUE TITLE
title 和 description 有什么特别要求？

### ISSUE THREAD

**Issue by ChenWeird** [liuyug/mdict-utils#8]
我使用 mdict -a dict.txt dict.mdx 可以正常打包。
但使用mdict --title title.html --description description.html -a dict.txt dict.mdx 就无法打包，扫描dict.txt后就闪退了。

title.html和description.html中都只是写了一行最普通的中文文字，没有任何html元素和特殊符号。

请教：title 和 description 有什么特别要求？

我使用python 3.7.5 x64, Win 10

**Comment by ChenWeird** [comment]
[demo and error.zip](https://github.com/liuyug/mdict-utils/files/5055585/demo.and.error.zip)

这是我用到的文件和命令，以及提示信息。

刚才也让其他网友测试了这个demo文件，他们在mac和linux下都没问题，可是我的在win下使用有问题。。。

**Comment by ChenWeird** [comment]
经过众多高人指点，目前找到两个解决方案：
1、在win下需要指定两个html文件的编码为gbk
2、修改程序：

![photo_2020-08-11_16-10-28](https://user-images.githubusercontent.com/25874852/89874008-d249b780-dbed-11ea-8d97-91529723e8f0.jpg)

感觉第二个方案比较好，规定统一都用UTF-8，避免用户对编码问题产生困扰。

**Comment by freemdict** [comment]
此问题是 在 [__main__.py](https://github.com/liuyug/mdict-utils/blob/master/mdict_utils/__main__.py) 文件的 121 和 123 行，未指定文件编码，windows下会以 GBK 读取导致。按上图增加编码即可。

**Comment by liuyug** [comment]
默认都使用 utf-8 编码。

程序已经更新
